### ISSUE TITLE
HashTag components issue & fix

### ISSUE THREAD

**Issue by moonchop** [ShareMate/sharemate-client#2]
## 원래 코드
`const HASHTAG_OBJ = [
  "rgb(219,156,218)",
  "rgb(175,173,245)",
  "rgb(186,152,229)",
]`

## 바꾼 코드
`const HASHTAG_OBJ = {
  red: "ring-[rgb(219,156,218)] text-[rgb(219,156,218)]",
  blue: "ring-[rgb(175,173,245)] text-[rgb(175,173,245)]",
  purple: "ring-[rgb(186,152,229)] text-[rgb(186,152,229)]",
};`

HashTag에 Text와 Color를 인자로 넘기도록 함.
## 바꾼 이유
ring-["더미 문자열"] 로 하면 tailwind는 css를 새로 만들지 않음.(이미 만들어져있는 css에서 찾음.)
지금까지 Color가 적용되었던 이유는 FeedTest에서 tailwind로 ring-@@을 만들어놨기 때문에 적용 된 것임.

**Comment by moonchop** [comment]
궁금한거 있거나, 이해하셨으면 댓글 달아주세요

**Comment by devnak** [comment]
확인 & 이해 완료했습니다. 감사합니다
